import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { signRequest } from "./auth.js";
import { adminRequest, findRunningServer, localBaseUrl } from "./client.js";
import { loadConfig, readRawConfig, setConfigValue, type Config, type RunnerName } from "./config.js";
import { ADMIN_TOKEN_ENV, defaultSecretEnvFor, loadSecrets, readEnvFile, upsertEnvVar, type Secrets } from "./env.js";
import { findExample } from "./examples.js";
import { parseFrontmatter, stringifyFrontmatter } from "./frontmatter.js";
import { generateSecret, newJobId } from "./ids.js";
import { JobStore, type JobRecord } from "./jobs.js";
import { silentLogger, type Logger } from "./logger.js";
import type { Paths } from "./paths.js";
import { redactHeaders, type Trigger, type WebhookEvent } from "./payload.js";
import { JobQueue } from "./queue.js";
import { resolveRunSettings } from "./run.js";
import { publicJob } from "./server.js";
import { loadProject, PROJECT_FILE_NAMES, renderProjectTemplate, resolveProject, type LoadedProject } from "./projects.js";
import { configProjects, SkillRegistry } from "./registry.js";
import { AUTH_TYPES, parseSkillDocument, renderSkillTemplate, skillFile, type AuthType, type NormalizedAuth, type Skill } from "./skills.js";
import { currentExposures, findTailscale } from "./tailscale.js";
import { displayPath, errorMessage, expandTilde, isValidSkillName } from "./util.js";

export interface Ops {
  paths: Paths;
  config: Config;
  secrets: () => Secrets;
  /** Secrets from the .env file only. */
  fileSecrets: () => Secrets;
  registry: SkillRegistry;
  store: JobStore;
  logger: Logger;
}

export function createOps(paths: Paths, options: { env?: NodeJS.ProcessEnv; logger?: Logger; config?: Config } = {}): Ops {
  const config = options.config ?? loadConfig(paths);
  return {
    paths,
    config,
    secrets: () => loadSecrets(paths, options.env ?? process.env),
    fileSecrets: () => readEnvFile(paths.envFile),
    registry: new SkillRegistry(paths.skillsDir, { projects: configProjects(paths) }),
    store: new JobStore(paths.jobsDir, { maxJobs: config.jobs.max_jobs, dedupeWindowSeconds: config.jobs.dedupe_window_seconds }),
    logger: options.logger ?? silentLogger,
  };
}

// ---------------------------------------------------------------------------
// Secrets
// ---------------------------------------------------------------------------

/** Auth schemes whose secret skillhook can invent (the sender is configured with it afterwards). */
export function skillhookManagesSecret(auth: NormalizedAuth): boolean {
  if (auth.type === "none") return false;
  if (auth.type === "hmac") return !auth.preset;
  return auth.type === "bearer" || auth.type === "basic";
}

/** Resolves `admin`, a skill name, or an ENV_VAR_NAME to the env var that holds the secret. */
export function resolveSecretName(ops: Ops, name: string): { env: string; skill?: Skill } {
  if (name === "admin") return { env: ADMIN_TOKEN_ENV };
  if (/^[A-Z_][A-Z0-9_]*$/.test(name)) return { env: name };
  if (isValidSkillName(name)) {
    const skill = ops.registry.get(name);
    if (skill && skill.auth.type !== "none") return { env: skill.auth.secret_env, skill };
    return { env: defaultSecretEnvFor(name), skill };
  }
  throw new Error(`"${name}" is neither a skill name nor an ENV_VAR_NAME`);
}

export interface SecretResult {
  env: string;
  /** The new value; only present when a value was generated by this call. */
  generated?: string;
  existed: boolean;
}

export function generateSecretFor(ops: Ops, name: string, options: { force?: boolean; bytes?: number } = {}): SecretResult {
  const { env } = resolveSecretName(ops, name);
  const existing = readEnvFile(ops.paths.envFile)[env];
  if (existing && !options.force) return { env, existed: true };
  const value = generateSecret(options.bytes ?? 32);
  upsertEnvVar(ops.paths.envFile, env, value);
  return { env, generated: value, existed: Boolean(existing) };
}

export function setSecret(ops: Ops, name: string, value: string): { env: string } {
  const { env } = resolveSecretName(ops, name);
  upsertEnvVar(ops.paths.envFile, env, value);
  return { env };
}

/** Makes sure a skill whose secret skillhook manages has one; provider-signed skills are left alone. */
export function ensureSkillSecret(ops: Ops, skill: Skill): SecretResult | undefined {
  if (!skillhookManagesSecret(skill.auth) || skill.auth.type === "none") return undefined;
  return generateSecretFor(ops, skill.auth.secret_env);
}

// ---------------------------------------------------------------------------
// Skills
// ---------------------------------------------------------------------------

export interface CreateSkillInput {
  name: string;
  description: string;
  instructions?: string;
  runner?: RunnerName;
  model?: string;
  effort?: string;
  authType?: AuthType;
  secretEnv?: string;
  cwd?: string;
  timeoutSeconds?: number;
  when?: unknown[];
  env?: string[];
  overwrite?: boolean;
  /** Skip creating a secret (for provider-signed auth you still have to `secret set` it). */
  noSecret?: boolean;
}

export interface CreateSkillResult {
  skill: Skill;
  file: string;
  created: boolean;
  secret?: SecretResult;
  /** What the sender must do to authenticate, for humans. */
  authNote: string;
}

export function createSkill(ops: Ops, input: CreateSkillInput): CreateSkillResult {
  if (!isValidSkillName(input.name)) throw new Error(`Invalid skill name "${input.name}": use 1-64 lowercase letters, digits and single hyphens`);
  if (input.authType && !AUTH_TYPES.includes(input.authType)) throw new Error(`Unknown auth type "${input.authType}". Known: ${AUTH_TYPES.join(", ")}`);
  const dir = path.join(ops.paths.skillsDir, input.name);
  const file = skillFile(dir);
  if (existsSync(file) && !input.overwrite) throw new Error(`Skill "${input.name}" already exists at ${file} (pass overwrite to replace it)`);
  let content = renderSkillTemplate({ name: input.name, description: input.description, runner: input.runner, model: input.model, authType: input.authType, cwd: input.cwd, instructions: input.instructions });
  // Extra structured fields go through the frontmatter parser so the file stays valid YAML.
  if (input.effort || input.timeoutSeconds || input.secretEnv || input.when?.length || input.env?.length) {
    const fm = parseFrontmatter(content);
    const block = (fm.data.skillhook ?? {}) as Record<string, unknown>;
    if (input.effort) block.effort = input.effort;
    if (input.timeoutSeconds) block.timeout_seconds = input.timeoutSeconds;
    if (input.secretEnv) block.auth = { ...((block.auth as Record<string, unknown>) ?? { type: input.authType ?? "bearer" }), secret_env: input.secretEnv };
    if (input.when?.length) block.when = input.when;
    if (input.env?.length) block.env = input.env;
    fm.data.skillhook = block;
    content = stringifyFrontmatter(fm.data, fm.body);
  }
  const skill = parseSkillDocument(content, dir); // validate before touching disk
  mkdirSync(dir, { recursive: true });
  writeFileSync(file, content);
  const loaded = ops.registry.get(input.name) ?? skill;
  const secret = input.noSecret ? undefined : ensureSkillSecret(ops, loaded);
  return { skill: loaded, file, created: true, secret, authNote: authNoteFor(loaded, secret) };
}

export function authNoteFor(skill: Skill, secret?: SecretResult): string {
  const auth = skill.auth;
  if (auth.type === "none") return "No authentication: anyone with the URL can trigger this skill. Consider allow_ips or a bearer token.";
  const envName = auth.secret_env;
  if (skillhookManagesSecret(auth)) {
    const how = auth.type === "bearer" ? (auth.header === "authorization" ? `Authorization: Bearer <secret>` : `${auth.header}: <secret>`) : auth.type === "basic" ? "HTTP Basic (user:password)" : `HMAC-${(auth as { algorithm: string }).algorithm.toUpperCase()} of the body in ${(auth as { header: string }).header}`;
    const state = secret?.generated ? "A fresh secret was generated" : `Secret ${envName} ${secret?.existed ? "already exists" : "is not set"}`;
    return `${state} in .env. Configure the sender to send ${how}. Show or rotate it with: skillhook secret generate ${skill.name} --force`;
  }
  return `Paste the signing secret from ${auth.type === "standard-webhooks" ? auth.preset ?? "the provider" : auth.type === "hmac" ? auth.preset ?? "the provider" : auth.type} into skillhook: skillhook secret set ${envName}`;
}

export function addExampleSkill(ops: Ops, exampleName: string, asName = exampleName): CreateSkillResult {
  const example = findExample(exampleName);
  if (!example) throw new Error(`No bundled example named "${exampleName}". Run: skillhook skills examples`);
  if (!isValidSkillName(asName)) throw new Error(`Invalid skill name "${asName}"`);
  const dir = path.join(ops.paths.skillsDir, asName);
  if (existsSync(dir)) throw new Error(`Skill "${asName}" already exists at ${dir}`);
  cpSync(example.dir, dir, { recursive: true });
  if (asName !== exampleName) {
    const text = readFileSync(skillFile(dir), "utf8").replace(/^name:\s*.*$/m, `name: ${asName}`);
    writeFileSync(skillFile(dir), text);
  }
  const skill = ops.registry.get(asName);
  if (!skill) throw new Error(`Example copied but failed to load from ${dir}`);
  const secret = ensureSkillSecret(ops, skill);
  return { skill, file: skillFile(dir), created: true, secret, authNote: authNoteFor(skill, secret) };
}

// ---------------------------------------------------------------------------
// Projects: repositories whose skillhook.yaml contributes hooks
// ---------------------------------------------------------------------------

/** The `projects` entries of skillhook.json as written (no defaults, no resolution). */
export function linkedProjectEntries(ops: Ops): string[] {
  const raw = readRawConfig(ops.paths).projects;
  return Array.isArray(raw) ? raw.filter((entry): entry is string => typeof entry === "string") : [];
}

function sameProject(a: string, b: string): boolean {
  return path.resolve(expandTilde(a)) === path.resolve(expandTilde(b));
}

/** Every linked project, loaded. */
export function listProjects(ops: Ops): LoadedProject[] {
  return ops.registry.projects();
}

export interface LinkResult {
  /** The absolute path written to skillhook.json (a directory, or the YAML file when one was named). */
  entry: string;
  project: LoadedProject;
  /** False when the project was linked before (the entry is left as it was). */
  added: boolean;
  /** Secrets generated for hooks whose auth skillhook manages (bearer, basic, generic hmac). */
  secrets: (SecretResult & { hook: string })[];
  /** Hooks whose name is already taken by another source, or that failed to compile. */
  errors: { name: string; error: string }[];
}

/**
 * Registers a directory's skillhook.yaml (or the file itself) in `projects` of skillhook.json. The file must
 * exist and parse; individual hook problems are reported, not fatal. The running server picks the hooks up
 * without a restart.
 */
export function linkProject(ops: Ops, dirOrFile: string, options: { noSecret?: boolean } = {}): LinkResult {
  const ref = resolveProject(dirOrFile);
  const entry = ref.file === resolveProject(ref.dir).file ? ref.dir : ref.file;
  const project = loadProject(entry);
  if (project.error) throw new Error(project.error);
  const current = linkedProjectEntries(ops);
  const added = !current.some((existing) => sameProject(existing, entry));
  if (added) setConfigValue(ops.paths, "projects", [...current, entry]);
  const secrets: LinkResult["secrets"] = [];
  if (!options.noSecret) {
    for (const hook of project.hooks) {
      const secret = ensureSkillSecret(ops, hook);
      if (secret) secrets.push({ ...secret, hook: hook.name });
    }
  }
  const listed = ops.registry.list();
  const errors = listed.errors.filter((e) => e.dir === project.dir).map((e) => ({ name: e.name, error: e.error }));
  return { entry, project, added, secrets, errors };
}

/** Removes a project from `projects`; the hooks stop routing (404) at once. Nothing in the project is touched. */
export function unlinkProject(ops: Ops, dirOrFile: string): { entry: string; removed: boolean } {
  const ref = resolveProject(dirOrFile);
  const current = linkedProjectEntries(ops);
  const kept = current.filter((existing) => !sameProject(existing, ref.dir) && !sameProject(existing, ref.file));
  const removed = kept.length !== current.length;
  if (removed) setConfigValue(ops.paths, "projects", kept.length ? kept : undefined);
  return { entry: ref.dir, removed };
}

export interface InitProjectResult {
  file: string;
  /** False when the file already existed and `force` was not set (nothing written). */
  written: boolean;
  link: LinkResult;
}

/** Writes a starter skillhook.yaml into a directory (creating it if needed) and links the project. */
export function initProject(ops: Ops, dir: string, options: { force?: boolean; noSecret?: boolean } = {}): InitProjectResult {
  const ref = resolveProject(dir);
  const existing = PROJECT_FILE_NAMES.map((name) => path.join(ref.dir, name)).find((candidate) => existsSync(candidate));
  const file = existing ?? path.join(ref.dir, PROJECT_FILE_NAMES[0]);
  const written = !existing || options.force === true;
  if (written) {
    mkdirSync(ref.dir, { recursive: true });
    writeFileSync(file, renderProjectTemplate());
  }
  return { file, written, link: linkProject(ops, ref.dir, { noSecret: options.noSecret }) };
}

/** `~/dev/api (skillhook.yaml)` for humans. */
export function describeProject(project: LoadedProject): string {
  return `${displayPath(project.dir)} (${path.basename(project.file)})`;
}

// ---------------------------------------------------------------------------
// Running skills
// ---------------------------------------------------------------------------

export interface ManualRunInput {
  skill: Skill;
  payload: unknown;
  headers?: Record<string, string>;
  query?: Record<string, string>;
  trigger: Trigger;
  overrides?: { runner?: RunnerName; model?: string; effort?: string; cwd?: string };
  /** Recorded on the job and the event; the caller is responsible for `rememberDelivery`. The scheduler uses `schedule:<slot>`. */
  deliveryId?: string;
  /** `source.method` on the job (default `LOCAL`; the scheduler writes `SCHEDULE`). */
  sourceMethod?: string;
}

export function buildManualEvent(input: ManualRunInput, id = newJobId()): WebhookEvent {
  const headers = { "content-type": typeof input.payload === "string" ? "text/plain" : "application/json", "user-agent": `skillhook-${input.trigger}`, ...(input.headers ?? {}) };
  const body = typeof input.payload === "string" ? input.payload : JSON.stringify(input.payload ?? null);
  return {
    id,
    skill: input.skill.name,
    trigger: input.trigger,
    received_at: new Date().toISOString(),
    method: "POST",
    path: `/hooks/${input.skill.name}`,
    query: input.query ?? {},
    headers: redactHeaders(headers),
    source_ip: "127.0.0.1",
    content_type: headers["content-type"],
    content_length: Buffer.byteLength(body),
    body_kind: typeof input.payload === "string" ? "text" : "json",
    delivery_id: input.deliveryId,
    payload: input.payload,
  };
}

/** Creates (but does not enqueue) a job for a run that did not arrive over HTTP. Needs only the config and the job store, so the scheduler can call it with the server's own instances. */
export function createManualJob(ops: Pick<Ops, "config" | "store">, input: ManualRunInput, store = ops.store): JobRecord {
  const settings = resolveRunSettings(input.skill, ops.config, input.overrides);
  const id = newJobId();
  const event = buildManualEvent(input, id);
  return store.create({
    id,
    skill: input.skill.name,
    trigger: input.trigger,
    runner: settings.runner,
    model: settings.model,
    effort: settings.effort,
    source: { ip: "127.0.0.1", method: input.sourceMethod ?? "LOCAL", path: event.path, content_type: event.content_type, user_agent: event.headers["user-agent"] },
    delivery_id: input.deliveryId,
    event,
  });
}

/** Runs one job in this process (a private queue) and resolves when it finishes or `waitMs` elapses. */
export async function runSkillLocally(ops: Ops, input: ManualRunInput & { waitMs?: number; onStart?: (job: JobRecord) => void }): Promise<JobRecord> {
  const config = { ...ops.config, concurrency: 1 };
  const queue = new JobQueue({ store: ops.store, config, registry: ops.registry, secrets: ops.secrets, fileSecrets: ops.fileSecrets, logger: ops.logger });
  const job = createManualJob(ops, input);
  input.onStart?.(job);
  queue.enqueue(job);
  const settings = resolveRunSettings(input.skill, ops.config, input.overrides);
  const waitMs = input.waitMs ?? (settings.timeoutSeconds + 30) * 1000;
  const finished = await queue.waitFor(job.id, waitMs);
  return finished ?? ops.store.require(job.id);
}

export interface ServerRunResult {
  baseUrl: string;
  status: number;
  body: unknown;
}

/** Triggers a skill through the running server's admin API; undefined when no server is running. */
export async function triggerViaServer(ops: Ops, input: { skill: Skill; payload: unknown; headers?: Record<string, string>; overrides?: { runner?: RunnerName; model?: string; effort?: string }; waitSeconds?: number }): Promise<ServerRunResult | undefined> {
  const running = await findRunningServer(ops.paths);
  if (!running) return undefined;
  const response = await adminRequest(running.baseUrl, ops.secrets(), `/skills/${input.skill.name}/run`, {
    method: "POST",
    body: { payload: input.payload, headers: input.headers, runner: input.overrides?.runner, model: input.overrides?.model, effort: input.overrides?.effort, wait: input.waitSeconds ?? 0 },
  });
  return { baseUrl: running.baseUrl, status: response.status, body: response.body };
}

// ---------------------------------------------------------------------------
// URLs and signed test deliveries
// ---------------------------------------------------------------------------

export type UrlSource = "config" | "tailscale" | "server" | "local";

export async function resolveBaseUrl(ops: Ops, options: { prefer?: "public" | "local" } = {}): Promise<{ baseUrl: string; source: UrlSource }> {
  if (options.prefer !== "local") {
    if (ops.config.public_url) return { baseUrl: ops.config.public_url.replace(/\/$/, ""), source: "config" };
    if (findTailscale()) {
      const exposures = await currentExposures();
      const ours = exposures.find((e) => e.target.endsWith(`:${ops.config.port}`) && e.path === "/") ?? exposures.find((e) => e.target.endsWith(`:${ops.config.port}`));
      if (ours) return { baseUrl: ours.url, source: "tailscale" };
    }
    if (options.prefer === "public") throw new Error("No public URL yet. Run: skillhook expose tailscale");
  }
  const running = await findRunningServer(ops.paths);
  if (running) return { baseUrl: running.baseUrl, source: "server" };
  return { baseUrl: localBaseUrl({ host: ops.config.host, port: ops.config.port }), source: "local" };
}

export function webhookUrl(baseUrl: string, skillName: string): string {
  return `${baseUrl.replace(/\/$/, "")}/hooks/${skillName}`;
}

export interface SendResult {
  url: string;
  status: number;
  body: unknown;
  /** Names of the auth headers that were attached (values are never returned). */
  signedHeaders: string[];
  job?: Record<string, unknown>;
}

/** Signs a payload exactly like the configured sender would and POSTs it to `/hooks/<skill>`. */
export async function sendSignedWebhook(ops: Ops, input: { skill: Skill; payload: unknown; baseUrl: string; waitSeconds?: number; headers?: Record<string, string> }): Promise<SendResult> {
  const { skill } = input;
  const bodyText = typeof input.payload === "string" ? input.payload : JSON.stringify(input.payload ?? {});
  const rawBody = Buffer.from(bodyText);
  let signed: Record<string, string> = {};
  if (skill.auth.type !== "none") {
    const secret = ops.secrets()[skill.auth.secret_env];
    if (!secret) throw new Error(`Secret ${skill.auth.secret_env} is not set. Run: skillhook secret generate ${skill.name}`);
    signed = signRequest(skill.auth, secret, rawBody);
  }
  const url = `${webhookUrl(input.baseUrl, skill.name)}${input.waitSeconds ? `?wait=${input.waitSeconds}` : ""}`;
  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { "content-type": typeof input.payload === "string" ? "text/plain" : "application/json", "user-agent": "skillhook-send", ...signed, ...(input.headers ?? {}) },
      body: rawBody,
      signal: AbortSignal.timeout(((input.waitSeconds ?? 0) + 30) * 1000),
    });
  } catch (error) {
    const cause = (error as { cause?: { message?: string; code?: string } }).cause;
    const detail = cause?.message ?? errorMessage(error);
    const hint = url.startsWith("https://") ? " If this URL was exposed moments ago, Tailscale may still be fetching its TLS certificate: wait ~30s and retry, or check `skillhook expose status`." : " Is the server running? (skillhook serve / skillhook service status)";
    throw new Error(`POST ${url} failed: ${detail}.${hint}`);
  }
  const text = await response.text();
  let body: unknown = text;
  try {
    body = JSON.parse(text);
  } catch {
    /* not JSON */
  }
  const job = typeof body === "object" && body !== null && "job" in body ? ((body as { job: Record<string, unknown> }).job) : undefined;
  return { url, status: response.status, body, signedHeaders: Object.keys(signed), job };
}

export { publicJob };
